networks:
  bookstack: null
  proxy:
    external: true
services:
  bookstack:
    environment:
      APP_KEY: ${app_key:?}
      APP_URL: https://bs.buncha.men
      DB_DATABASE: ${db_name:-bookstack}
      DB_HOST: bookstack_db:3306
      DB_PASSWORD: ${db_pass:?}
      DB_USERNAME: ${db_user:-bookstack}
    image: solidnerd/bookstack:${bookstack_version:-26.3}
    deploy:
      labels:
        homepage.group: Personal
        homepage.href: https://bs.buncha.men
        homepage.icon: sh-bookstack.svg
        homepage.name: Bookstack
        kuma.__docker:
        release_notes: "https://codeberg.org/bookstack/bookstack/releases"
        traefik.enable: "true"
        traefik.http.routers.bookstack.entryPoints: "https"
        traefik.http.routers.bookstack.middlewares: "localonly@file"
        traefik.http.routers.bookstack.rule: "Host(`bs.buncha.men`)"
        traefik.http.services.bookstack.loadbalancer.server.port: 8080
    networks:
      bookstack: null
      proxy: null
    volumes:
      - /mnt/docker/bookstack/public_uploads:/var/www/bookstack/public/uploads:rw
      - /mnt/docker/bookstack/storage_uploads:/var/www/bookstack/storage/uploads:rw
  bookstack_db:
    image: mariadb:${mariadb_version:-12}
    environment:
      MARIADB_DATABASE: ${db_name:-bookstack}
      MARIADB_PASSWORD: ${db_pass:?}
      MARIADB_ROOT_PASSWORD: ${root_pass:?}
      MARIADB_USER: ${db_user:-bookstack}
      MARIADB_AUTO_UPGRADE: true
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://mariadb.com/docs/release-notes/community-server"
    networks:
      bookstack: null
    volumes:
      - /mnt/docker/bookstack/db:/var/lib/mysql:rw
