networks:
  default: null
  proxy:
    external: true
services:
  rxresume:
    environment:
      APP_URL: https://rx.buncha.men
      AUTH_SECRET: ${auth_secret:?}
      DATABASE_URL: postgresql://${db_user:-rxresume}:${db_pass:?}@rxresume_postgres:5432/${db_name:-rxresume}
      TZ: ${timezone:-Etc/UTC}
    image: ghcr.io/amruthpillai/reactive-resume:${rxresume_version:-v5}
    labels:
      homepage.group: Personal
      homepage.href: https://rx.buncha.men
      homepage.icon: sh-reactive-resume.svg
      homepage.name: RxResume
      kuma.__docker:
      release_notes: "https://github.com/amruthpillai/reactive-resume/releases"
      traefik.enable: "true"
      traefik.http.routers.rxresume.entrypoints: "https"
      traefik.http.routers.rxresume.middlewares: "allowedIPs@file,tinyauth@file"
      traefik.http.routers.rxresume.rule: "Host(`rx.buncha.men`)"
      traefik.http.services.rxresume.loadbalancer.server.port: 3000
    networks:
      default: null
      proxy: null
    volumes:
      - ${data:-.}/data:/app/data
  rxresume_postgres:
    environment:
      POSTGRES_DB: ${db_name:-rxresume}
      POSTGRES_USER: ${db_user:-rxresume}
      POSTGRES_PASSWORD: ${db_pass:?}
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      timeout: 5s
    image: postgres:${postgres_version:-16-alpine}
    labels:
      kuma.__docker:
      release_notes: "https://www.postgresql.org/docs/release/"
    networks:
      default: null
    volumes:
      - ${data:-.}/db:/var/lib/postgresql/data
