networks:
  proxy:
    external: true
services:
  ittools:
    image: "sharevb/it-tools:${ittools_version:-latest}"
    deploy:
      labels:
        homepage.group: Development
        homepage.href: https://it.buncha.men
        homepage.icon: sh-it-tools.svg
        homepage.name: ItTools
        kuma.__docker:
        release_notes: "https://github.com/CorentinTh/it-tools/releases"
        traefik.enable: "true"
        traefik.http.routers.ittools.entryPoints: "https"
        traefik.http.routers.ittools.middlewares: "allowedIPs@file"
        traefik.http.routers.ittools.rule: "Host(`it.buncha.men`)"
        traefik.http.services.ittools.loadbalancer.server.port: 8080
    networks:
      proxy: null
