networks:
  default:
    driver: bridge
services:
  gluetun_proxy:
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      HTTPPROXY: on
      SERVER_CITIES: ${cities:-Stockholm}
      TZ: ${timezone:-UTC}
      VPN_SERVICE_PROVIDER: ${provider:?}
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${wgkey:?}
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    image: qmcgaw/gluetun:${gluetun_version:-v3.41}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://github.com/qdm12/gluetun/releases"
    ports:
      - "${listen_interface:-0.0.0.0}:1080:1080/tcp"
      - "${listen_interface:-0.0.0.0}:8888:8888/tcp"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${disable_ipv6:-0}
    volumes:
      - /mnt/docker/gluetun-proxy:/gluetun:rw
  socks5proxy:
    environment:
      ALLOWED_IPS: ${allowed_ips}
      PROXY_PASS: ${proxy_pass:?}
      PROXY_USER: ${proxy_user:?}
      REQUIRE_AUTH: ${enable_auth:-true}
    image: serjs/go-socks5-proxy:${socks5proxy_version:-latest}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://github.com/serjs/socks5-server/releases"
    network_mode: service:gluetun_proxy
