networks:
  default: null
  proxy:
    external: true
services:
  paperlessngx:
    environment:
      PAPERLESS_DBHOST: paperlessngx_db
      PAPERLESS_DBNAME: ${db_name:-paperless}
      PAPERLESS_DBPASS: ${db_pass:?}
      PAPERLESS_DBUSER: ${db_user:-paperless}
      PAPERLESS_REDIS: redis://paperlessngx_valkey:6379
      PAPERLESS_SECRET_KEY: ${secret_key:?}
      PAPERLESS_TIME_ZONE: ${timezone:-UTC}
      PAPERLESS_URL: https://pl.buncha.men
      USERMAP_GID: ${gid:-1000}
      USERMAP_UID: ${uid:-1000}
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"SCOPE":["openid","profile","email"],"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"pocket-id","name":"Pocket-ID","client_id":"${client_id:?}","secret":"${client_secret:?}","settings":{"server_url":"https://id.buncha.men"}}]}}'
    image: ghcr.io/paperless-ngx/paperless-ngx:${paperlessngx_version:-latest}
    deploy:
      labels:
        homepage.group: Personal
        homepage.href: https://pl.buncha.men
        homepage.icon: sh-paperless-ngx.svg
        homepage.name: Paperless
        kuma.__docker:
        release_notes: "https://github.com/paperless-ngx/paperless-ngx/releases"
        traefik.enable: "true"
        traefik.http.routers.paperlessngx.entryPoints: "https"
        traefik.http.routers.paperlessngx.middlewares: "allowedIPs@file,tinyauth@file"
        traefik.http.routers.paperlessngx.rule: "Host(`pl.buncha.men`)"
        traefik.http.services.paperlessngx.loadbalancer.server.port: 8000
    networks:
      proxy: null
      default: null
    volumes:
      - /mnt/docker/paperless/app:/usr/src/paperless
  paperlessngx_db:
    environment:
      POSTGRES_DB: ${db_name:-paperless}
      POSTGRES_PASSWORD: ${db_pass:?}
      POSTGRES_USER: ${db_user:-paperless}
    image: docker.io/library/postgres:${postgres_version:-16}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://www.postgresql.org/docs/release/"
    networks:
      default: null
    volumes:
      - /mnt/docker/paperless/db:/var/lib/postgresql/data
  paperlessngx_valkey:
    image: valkey/valkey:${valkey_version:-9}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://github.com/valkey-io/valkey/releases"
    networks:
      default: null
    volumes:
      - /mnt/docker/paperless/valkey:/data
