networks:
  proxy:
    external: true
x-common-settings: &common-settings
  logging:
    driver: local
    options:
      compress: "true"
      max-file: "3"
      max-size: "10m"
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true
  stdin_open: false
  tty: false
services:
  vaultwarden:
    <<: *common-settings
    cap_drop:
      - ALL
    container_name: vaultwarden
    environment:
      ADMIN_TOKEN: "${vaultwarden_admin_token:?}"
      DOMAIN: https://vw.${domain:?}
    image: vaultwarden/server:${vaultwarden_version:-latest}
    labels:
      homepage.group: Personal
      homepage.href: https://vw.${domain:?}
      homepage.icon: sh-vaultwarden.svg
      homepage.name: Vaultwarden
      kuma.__docker:
      release_notes: "https://github.com/dani-garcia/vaultwarden/releases"
      traefik.enable: "true"
      traefik.http.routers.vaultwarden.entryPoints: "https"
      traefik.http.routers.vaultwarden.middlewares: "allowedIPs@file"
      traefik.http.routers.vaultwarden.priority: 30
      traefik.http.routers.vaultwarden.rule: "Host(`vw.${domain:?}`)"
      traefik.http.services.vaultwarden.loadbalancer.server.url: "http://vaultwarden:80"
      # Block admin page with tinyauth
      traefik.http.routers.vaultwarden-admin.entrypoints: "https"
      traefik.http.routers.vaultwarden-admin.middlewares: "allowedIPs@file,tinyauth@file"
      traefik.http.routers.vaultwarden-admin.priority: 50
      traefik.http.routers.vaultwarden-admin.rule: Host(`vw.${domain:?}`) && PathPrefix(`/admin`)
    networks:
      proxy:
    volumes:
      - ${data:-.}/vault/data:/data
