networks:
  proxy:
    external: true
services:
  vaultwarden:
    environment:
      ADMIN_TOKEN: "${vaultwarden_admin_token:?}"
      DOMAIN: https://vw.buncha.men
    image: vaultwarden/server:${vaultwarden_version:-latest}
    deploy:
      labels:
        homepage.group: Personal
        homepage.href: https://vw.buncha.men
        homepage.icon: sh-vaultwarden.svg
        homepage.name: Vaultwarden
        kuma.__docker:
        release_notes: "https://github.com/dani-garcia/vaultwarden/releases"
        traefik.enable: "true"
        traefik.http.routers.vaultwarden.entryPoints: "https"
        traefik.http.routers.vaultwarden.middlewares: "allowedIPs@file"
        traefik.http.routers.vaultwarden.priority: 30
        traefik.http.routers.vaultwarden.rule: "Host(`vw.buncha.men`)"
        traefik.http.services.vaultwarden.loadbalancer.server.port: 80
        # Block admin page with tinyauth
        traefik.http.routers.vaultwarden-admin.entrypoints: "https"
        traefik.http.routers.vaultwarden-admin.middlewares: "allowedIPs@file,tinyauth@file"
        traefik.http.routers.vaultwarden-admin.priority: 50
        traefik.http.routers.vaultwarden-admin.rule: Host(`vw.buncha.men`) && PathPrefix(`/admin`)
    networks:
      proxy:
    volumes:
      - /mnt/docker/vaultwarden:/data
