networks:
  default: null
  proxy:
    external: true
services:
  adguardhome:
    dns:
      - 9.9.9.9
      - 1.1.1.1
      - "2620:fe::fe"
      - "2606:4700:4700::1111"
    image: adguard/adguardhome:${adguard_version:-latest}
    deploy:
      labels:
        homepage.group: DNS
        homepage.href: https://ad.buncha.men
        homepage.icon: sh-adguard-home.svg
        homepage.name: Adguard - Komodo
        kuma.__docker:
        release_notes: "https://github.com/AdguardTeam/AdGuardHome/releases"
        traefik.enable: "true"
        traefik.http.routers.adguardhome.entryPoints: "https"
        traefik.http.routers.adguardhome.middlewares: "localonly@file"
        traefik.http.routers.adguardhome.rule: "Host(`ad.buncha.men`)"
        traefik.http.services.adguardhome.loadbalancer.server.port: 3000
    networks:
      default: null
      proxy: null
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /mnt/docker/adguardhome/work:/opt/adguardhome/work
      - /mnt/docker/adguardhome/conf:/opt/adguardhome/conf
  adguardhome-sync:
    command: run --config /config/adguardhome-sync.yml
    environment:
      LOG_LEVEL: ${log_level:-warn}
    image: ghcr.io/bakito/adguardhome-sync:${adguard_sync_version:-main}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://github.com/bakito/adguardhome-sync/releases"
    networks:
      default: null
    volumes:
      - /mnt/docker/adguardhome/adguardhome-sync.yml:/config/adguardhome-sync.yml
