networks:
  proxy:
    external: true
  socket-proxy:
    external: true
services:
  forgejo:
    environment:
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: forgejo_db:5432
      FORGEJO__database__NAME: ${db_name:-forgejo}
      FORGEJO__database__PASSWD: ${db_pass:?}
      FORGEJO__database__USER: ${db_user:-forgejo}
      FORGEJO__migrations__ALLOW_LOCALNETWORKS: true
      USER_GID: ${gid:-1000}
      USER_UID: ${uid:-1000}
    image: codeberg.org/forgejo/forgejo:${forgejo_version:-15-rootless}
    deploy:
      labels:
        homepage.group: Development
        homepage.href: https://fj.buncha.men
        homepage.icon: sh-forgejo.svg
        homepage.name: Forgejo
        kuma.__docker:
        release_notes: "https://codeberg.org/forgejo/forgejo/src/branch/forgejo/release-notes-published"
        traefik.enable: "true"
        traefik.http.routers.forgejo.entryPoints: "https"
        traefik.http.routers.forgejo.rule: "Host(`fj.buncha.men`)"
        traefik.http.services.forgejo.loadbalancer.server.port: 3000
    networks:
      default:
      proxy:
    ports:
      - "2222:2222/tcp" # Rootless ssh port
    user: ${uid:-1000}:${gid:-1000}
    volumes:
      - /mnt/docker/forgejo/app/data:/var/lib/gitea
      - /mnt/docker/forgejo/app/conf:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  forgejo_db:
    environment:
      POSTGRES_DB: ${db_name:-forgejo}
      POSTGRES_PASSWORD: ${db_pass:?}
      POSTGRES_USER: ${db_user:-forgejo}
    image: postgres:${postgres_version:-14}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://www.postgresql.org/docs/release/"
    networks:
      default:
    volumes:
      - /mnt/docker/forgejo/db:/var/lib/postgresql/data
  forgejo_runner:
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      GITEA_INSTANCE_URL: https://fj.buncha.men/
      GITEA_RUNNER_LABELS:
        "docker:docker://data.forgejo.org/oci/node:20-bullseye,\
        ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest,\
        ubuntu-22.04:docker://docker.gitea.com/runner-images:ubuntu-22.04,\
        ubuntu-20.04:docker://docker.gitea.com/runner-images:ubuntu-20.04"
      GITEA_RUNNER_NAME: forgejo_runner
      GITEA_RUNNER_REGISTRATION_TOKEN: ${token}
    image: gitea/act_runner:${runner_version:-nightly}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://gitea.com/gitea/runner/releases"
    networks:
      default: null
      socket-proxy: null
    volumes:
      - /mnt/docker/forgejo/runner:/data
