networks:
  proxy:
    external: true
  socket-proxy:
    external: true
services:
  pocketid:
    environment:
      APP_URL: https://id.dellhplaptop.xyz
      ENCRYPTION_KEY: ${pocketid_enc_key:?}
      PGID: ${gid:-1000}
      PUID: ${uid:-1000}
      TRUST_PROXY: "true"
    healthcheck:
      interval: 1m30s
      retries: 2
      start_period: 10s
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      timeout: 5s
    image: ghcr.io/pocket-id/pocket-id:${pocketid_version:-v2}
    deploy:
      labels:
        homepage.group: Access & Security
        homepage.href: https://id.dellhplaptop.xyz
        homepage.icon: sh-pocket-id.svg
        homepage.name: PocketID
        kuma.__docker:
        release_notes: "https://pocket-id.org/changelog"
        traefik.enable: "true"
        traefik.http.routers.pocketid.entryPoints: "https"
        traefik.http.routers.pocketid.rule: "Host(`id.dellhplaptop.xyz`)"
        traefik.http.services.pocketid.loadbalancer.server.port: 1411
      placement:
        constraints:
          - node.hostname == node-2
      update_config:
        order: stop-first
    networks:
      proxy:
    volumes:
      - pocketid:/app/data
  socket-proxy:
    environment:
      CONTAINERS: 1
      EVENTS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      NODES: 1
      POST: 1
      SERVICES: 1
      TASKS: 1
      TZ: ${timezone:-UTC}
      VOLUMES: 1
    image: ghcr.io/tecnativa/docker-socket-proxy:${socket_proxy_version:-latest}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        kuma.__docker:
        release_notes: "https://github.com/Tecnativa/docker-socket-proxy/releases"
    networks:
      socket-proxy:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  tinyauth:
    environment:
      TINYAUTH_APPURL: https://auth.dellhplaptop.xyz
      TINYAUTH_DATABASE_DRIVER: memory
      TINYAUTH_OAUTH_AUTOREDIRECT: pocketid
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: https://id.dellhplaptop.xyz/authorize
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ${tinyauth_id}
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ${tinyauth_secret}
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: Pocket ID
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: https://auth.dellhplaptop.xyz/api/oauth/callback/pocketid
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: openid email profile groups
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: https://id.dellhplaptop.xyz/api/oidc/token
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: https://id.dellhplaptop.xyz/api/oidc/userinfo
    image: ghcr.io/tinyauthapp/tinyauth:${tinyauth_version:-v5}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://tinyauth.app/docs/reference/changelog/"
        traefik.enable: "true"
        traefik.http.routers.tinyauth.entryPoints: "https"
        traefik.http.routers.tinyauth.rule: "Host(`auth.dellhplaptop.xyz`)"
        traefik.http.services.tinyauth.loadbalancer.server.port: 3000
    networks:
      proxy:
  traefik:
    environment:
      CF_DNS_API_TOKEN: ${cf_dns_api_token:?}
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS:?}
    image: traefik:${traefik_version:-v3.7}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        homepage.group: Access & Security
        homepage.href: https://tf.dellhplaptop.xyz
        homepage.icon: sh-traefik.svg
        homepage.name: Traefik
        kuma.__docker:
        release_notes: "https://github.com/traefik/traefik/releases"
        traefik.enable: "true"
        traefik.http.middlewares.tinyauth.forwardAuth.address: "http://tinyauth:3000/api/auth/traefik"
        traefik.http.middlewares.tinyauth.forwardAuth.authResponseHeaders: "remote-user"
        traefik.http.middlewares.tinyauth.forwardAuth.maxResponseBodySize: 104857600
        traefik.http.middlewares.tinyauth.forwardAuth.trustForwardHeader: "true"
        traefik.http.routers.traefik.entryPoints: "https"
        traefik.http.routers.traefik.middlewares: "localonly@file"
        traefik.http.routers.traefik.rule: "Host(`tf.dellhplaptop.xyz`)"
        traefik.http.routers.traefik.service: "api@internal"
        traefik.http.services.traefik.loadbalancer.server.port: 8080
    networks:
      proxy:
      socket-proxy:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
      - target: 7777
        published: 7777
        protocol: tcp
        mode: host
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/docker/traefik:/etc/traefik:rw
      - traefik_logs:/var/log/traefik:rw
volumes:
  pocketid:
  traefik_logs:
