networks:
  proxy:
    external: true
  socket-proxy:
    external: true
services:
  socket-proxy:
    extends:
      file: ../common.yaml
      service: base
    cap_drop:
      - ALL
    container_name: socket-proxy
    environment:
      CONTAINERS: 1
      EVENTS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      POST: 1
      TZ: ${timezone:-UTC}
      VOLUMES: 1
    image: ghcr.io/tecnativa/docker-socket-proxy:${socket_proxy_version:-latest}
    labels:
      kuma.__docker:
      release_notes: "https://github.com/Tecnativa/docker-socket-proxy/releases"
    networks:
      socket-proxy:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  traefik:
    extends:
      file: ../common.yaml
      service: base
    cap_drop:
      - ALL
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${cf_dns_api_token:?}
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS:?}
    image: traefik:${traefik_version:-v3.7}
    labels:
      homepage.group: Access & Security
      homepage.href: https://tf.dellhplaptop.xyz
      homepage.icon: sh-traefik.svg
      homepage.name: Traefik
      kuma.__docker:
      release_notes: "https://github.com/traefik/traefik/releases"
      traefik.enable: "true"
      traefik.http.routers.traefik.entryPoints: "https"
      traefik.http.routers.traefik.middlewares: "localonly@file"
      traefik.http.routers.traefik.rule: "Host(`tf.dellhplaptop.xyz`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.services.traefik.loadbalancer.server.url: "http://traefik:8080"
    networks:
      proxy:
      socket-proxy:
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "7777:7777/tcp"
      - "25565:25565/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${data:-.}/traefik/traefik.yml:/traefik.yml:ro
      - ${data:-.}/traefik/dynamic.yml:/dynamic.yml:ro
      - ${data:-.}/traefik/acme.json:/acme.json:rw
      - ${data:-.}/logs/traefik:/var/log/traefik:rw
