networks:
  proxy:
    external: true
services:
  rxresume:
    environment:
      APP_URL: https://rx.dellhplaptop.xyz
      AUTH_SECRET: ${auth_secret:?}
      DATABASE_URL: postgresql://${db_user:-rxresume}:${db_pass:?}@${db_host:?}:${db_port:-5432}/${db_name:-rxresume}
      TZ: ${timezone:-Etc/UTC}
    image: ghcr.io/amruthpillai/reactive-resume:${rxresume_version:-v5}
    deploy:
      placement:
        constraints:
          - node.hostname == node-1
      labels:
        homepage.group: Personal
        homepage.href: https://rx.dellhplaptop.xyz
        homepage.icon: sh-reactive-resume.svg
        homepage.name: RxResume
        kuma.__docker:
        release_notes: "https://github.com/amruthpillai/reactive-resume/releases"
        traefik.enable: "true"
        traefik.http.routers.rxresume.entrypoints: "https"
        traefik.http.routers.rxresume.middlewares: "allowedIPs@file"
        traefik.http.routers.rxresume.rule: "Host(`rx.dellhplaptop.xyz`)"
        traefik.http.services.rxresume.loadbalancer.server.port: 3000
    networks:
      proxy: null
    volumes:
      - /etc/docker/rxresume:/app/data
