networks:
  proxy:
    external: true
  socket-proxy:
    external: true
services:
  homepage:
    environment:
      TZ: ${timezone:-UTC}
      HOMEPAGE_ALLOWED_HOSTS: home.buncha.men
    image: ghcr.io/gethomepage/homepage:${homepage_version:-latest}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://github.com/gethomepage/homepage/releases"
        traefik.enable: "true"
        traefik.http.routers.homepage.entryPoints: "https"
        traefik.http.routers.homepage.middlewares: "localonly@file"
        traefik.http.routers.homepage.rule: "Host(`home.buncha.men`)"
        traefik.http.services.homepage.loadbalancer.server.port: 3000
    networks:
      proxy:
      socket-proxy:
    volumes:
      - /mnt/docker/homepage:/app/config:rw
  mywebsite:
    environment:
      BETTER_AUTH_SECRET: ${auth_secret:?}
      BETTER_AUTH_URL: https://www.buncha.men
      ORIGIN: https://www.buncha.men
    image: dellhplaptop/newwebsite:${mywebsite_version:-latest}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://fj.dellhplaptop.xyz/wleeper13/NewWebsite/releases"
        traefik.enable: "true"
        traefik.http.routers.mywebsite.entryPoints: "https"
        traefik.http.routers.mywebsite.middlewares: "allowedIPs@file"
        traefik.http.routers.mywebsite.rule: "Host(`www.buncha.men`)"
        traefik.http.services.mywebsite.loadbalancer.server.port: 3000
    networks:
      proxy:
    user: ${uid:-1000}:${gid:-1000}
    volumes:
      - /mnt/docker/newweb:/app/data
