networks:
  freshrss: null
  proxy:
    external: true
  socket-proxy:
    external: true
x-common-settings: &common-settings
  logging:
    driver: local
    options:
      compress: "true"
      max-file: "3"
      max-size: "10m"
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true
  stdin_open: false
  tty: false
services:
  copyparty:
    <<: *common-settings
    cap_drop:
      - ALL
    container_name: copyparty
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.2
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
    image: copyparty/iv:${copyparty_version:-latest}
    labels:
      homepage.group: Files & Sharing
      homepage.href: https://c.${domain:?}
      homepage.icon: sh-copyparty.svg
      homepage.name: Copyparty
      kuma.__docker:
      # kuma.__web: '"c.${domain:?}"'
      release_notes: "https://github.com/9001/copyparty/releases"
      traefik.enable: "true"
      traefik.http.routers.copyparty.entryPoints: "https"
      traefik.http.routers.copyparty.middlewares: "localonly@file"
      traefik.http.routers.copyparty.rule: "Host(`c.${domain:?}`)"
      traefik.http.services.copyparty.loadbalancer.server.url: "http://copyparty:3923"
    networks:
      proxy:
    stop_grace_period: 15s # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    user: ${uid:-1000}:${gid:-1000}
    volumes:
      - ${data:-.}/copyparty/conf:/cfg
      - ${data:-.}/copyparty/files:/w
  freshrss:
    <<: *common-settings
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    container_name: freshrss
    depends_on:
      - freshrss_postgres
    environment:
      CRON_MIN: "1,31"
      LISTEN: 0.0.0.0:80
      OIDC_CLIENT_ID: ${client_id:?}
      OIDC_CLIENT_SECRET: ${client_secret:?}
      OIDC_ENABLED: 1
      OIDC_PROVIDER_METADATA_URL: https://id.${domain:?}/.well-known/openid-configuration
      OIDC_REMOTE_USER_CLAIM: preferred_username
      OIDC_SCOPES: openid email profile
      OIDC_X_FORWARDED_HEADERS: X-Forwarded-Proto X-Forwarded-Host
      TRUSTED_PROXY: 0
      TZ: ${timezone:-UTC}
    image: freshrss/freshrss:${freshrss_version:-latest}
    labels:
      homepage.group: Personal
      homepage.href: https://rss.${domain:?}
      homepage.icon: sh-freshrss.svg
      homepage.name: Freshrss
      homepage.widget.password: ${freshrss_user_password:?}
      homepage.widget.type: freshrss
      homepage.widget.url: http://freshrss:80
      homepage.widget.username: ${freshrss_user_name:?}
      kuma.__docker:
      # kuma.__web: '"rss.${domain:?}"'
      release_notes: "https://github.com/linuxserver/docker-freshrss/releases"
      traefik.enable: "true"
      traefik.http.routers.freshrss.entryPoints: "https"
      traefik.http.routers.freshrss.middlewares: "allowedIPs@file"
      traefik.http.routers.freshrss.rule: "Host(`rss.${domain:?}`)"
      traefik.http.services.freshrss.loadbalancer.server.url: "http://freshrss:80"
    networks:
      freshrss:
      proxy:
    volumes:
      - ${data:-.}/rss/data:/var/www/FreshRSS/data
      - ${data:-.}/rss/extensions:/var/www/FreshRSS/extensions
  freshrss_postgres:
    <<: *common-settings
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    container_name: freshrss_postgres
    environment:
      POSTGRES_DB: ${db_name:-freshrss}
      POSTGRES_PASSWORD: ${db_pass:?}
      POSTGRES_USER: ${db_user:-freshrss}
    image: postgres:${postgres_version:-16}
    labels:
      kuma.__docker:
      release_notes: "https://www.postgresql.org/docs/release/"
    networks:
      freshrss:
    volumes:
      - ${data:-.}/rss/db:/var/lib/postgresql/data
  homepage:
    <<: *common-settings
    cap_drop:
      - ALL
    container_name: homepage
    environment:
      TZ: ${timezone:-UTC}
      HOMEPAGE_ALLOWED_HOSTS: home.${domain:?}
    image: ghcr.io/gethomepage/homepage:${homepage_version:-latest}
    labels:
      kuma.__docker:
      # kuma.__web: '"home.${domain:?}"'
      release_notes: "https://github.com/gethomepage/homepage/releases"
      traefik.enable: "true"
      traefik.http.routers.homepage.entryPoints: "https"
      traefik.http.routers.homepage.middlewares: "localonly@file"
      traefik.http.routers.homepage.rule: "Host(`home.${domain:?}`)"
      traefik.http.services.homepage.loadbalancer.server.url: "http://homepage:3000"
    networks:
      proxy:
      socket-proxy:
    volumes:
      - ${data:-.}/homepage:/app/config:rw
  mywebsite:
    <<: *common-settings
    cap_drop:
      - ALL
    container_name: mywebsite
    environment:
      BETTER_AUTH_SECRET: ${auth_secret:?}
      BETTER_AUTH_URL: https://www.${domain:?}
      ORIGIN: https://www.${domain:?}
    image: dellhplaptop/newwebsite:${mywebsite_version:-latest}
    labels:
      kuma.__docker:
      # kuma.__web: '"${domain:?}"'
      release_notes: "https://fj.dellhplaptop.xyz/wleeper13/NewWebsite/releases"
      traefik.enable: "true"
      traefik.http.routers.mywebsite.entryPoints: "https"
      traefik.http.routers.mywebsite.middlewares: "allowedIPs@file"
      traefik.http.routers.mywebsite.rule: "Host(`www.${domain:?}`)"
      traefik.http.services.mywebsite.loadbalancer.server.url: "http://mywebsite:3000"
    networks:
      proxy:
    user: ${uid:-1000}:${gid:-1000}
    volumes:
      - ${data:-.}/newweb/db:/app/data
  vaultwarden:
    <<: *common-settings
    cap_drop:
      - ALL
    container_name: vaultwarden
    environment:
      ADMIN_TOKEN: "${vaultwarden_admin_token:?}"
      DOMAIN: https://vw.${domain:?}
    image: vaultwarden/server:${vaultwarden_version:-latest}
    labels:
      homepage.group: Personal
      homepage.href: https://vw.${domain:?}
      homepage.icon: sh-vaultwarden.svg
      homepage.name: Vaultwarden
      kuma.__docker:
      # kuma.__web: '"vw.${domain:?}"'
      release_notes: "https://github.com/dani-garcia/vaultwarden/releases"
      traefik.enable: "true"
      traefik.http.routers.vaultwarden.entryPoints: "https"
      traefik.http.routers.vaultwarden.middlewares: "allowedIPs@file"
      traefik.http.routers.vaultwarden.priority: 30
      traefik.http.routers.vaultwarden.rule: "Host(`vw.${domain:?}`)"
      traefik.http.services.vaultwarden.loadbalancer.server.url: "http://vaultwarden:80"
      # Block admin page with tinyauth
      traefik.http.routers.vaultwarden-admin.entrypoints: "https"
      traefik.http.routers.vaultwarden-admin.middlewares: "allowedIPs@file,tinyauth@file"
      traefik.http.routers.vaultwarden-admin.priority: 50
      traefik.http.routers.vaultwarden-admin.rule: Host(`vw.${domain:?}`) && PathPrefix(`/admin`)
    networks:
      proxy:
    volumes:
      - ${data:-.}/vault/data:/data
