networks:
  default:
  proxy:
    external: true
services:
  ollama:
    extends:
      file: ../common.yaml
      service: base
    cap_drop:
      - ALL
    container_name: ollama
    environment:
       OLLAMA_HOST: 0.0.0.0:11434
    image: ollama/ollama:${ollama_version:-latest}
    labels:
      release_notes: "https://github.com/ollama/ollama/releases"
      kuma.__docker:
    networks:
      default:
    volumes:
       - ${data:-.}/ollama_data:/root/.ollama
  openwebui:
    extends:
      file: ../common.yaml
      service: base
    cap_drop:
      - ALL
    container_name: openwebui
    depends_on:
      - ollama
    environment:
      DEFAULT_USER_ROLE: user
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_URL: https://ai.dellhplaptop.xyz
    image: ghcr.io/open-webui/open-webui:${openwebui_version:-main}
    labels:
      homepage.group: Tools
      homepage.href: https://ai.dellhplaptop.xyz
      homepage.icon: sh-open-webui.svg
      homepage.name: OpenWebUI
      kuma.__docker:
      release_notes: "https://github.com/open-webui/open-webui/releases"
      traefik.enable: "true"
      traefik.http.routers.openwebui.entryPoints: "https"
      traefik.http.routers.openwebui.middlewares: "localonly@file"
      traefik.http.routers.openwebui.rule: "Host(`ai.dellhplaptop.xyz`)"
      traefik.http.routers.openwebui.tls.certresolver: "cloudflare"
      traefik.http.services.openwebui.loadbalancer.server.url: "http://openwebui:8080"
    networks:
      default:
      proxy:
    volumes:
      - ${data:-.}/openwebui:/app/backend/data
