networks:
  proxy:
    external: true
services:
  garage:
    extends:
      file: ../common.yaml
      service: base
    cap_drop:
      - ALL
    container_name: garage
    environment:
      TZ: ${timezone:-UTC}
    image: dxflrs/garage:${garage_version:-v2.3.0}
    labels:
      kuma.__docker:
      kuma.garage_s3.port.hostname: garage
      kuma.garage_s3.port.name: port_garage_s3
      kuma.garage_s3.port.notification_name_list: '["ntfy"]'
      kuma.garage_s3.port.port: 3900
      release_notes: "https://git.deuxfleurs.fr/Deuxfleurs/garage/releases"
      traefik.enable: "true"
      traefik.http.routers.garage.entryPoints: "https"
      traefik.http.routers.garage.middlewares: "localonly@file"
      traefik.http.routers.garage.rule: "Host(`s3.${domain:?}`)"
      traefik.http.services.garage.loadbalancer.server.url: "http://garage:3900"
    networks:
      proxy:
    ports:
      - "3900:3900/tcp" ## s3 api
      - "3901:3901/tcp" ## rpc
    volumes:
      - ${data:-.}/garage.toml:/etc/garage.toml:ro
      - ${data:-.}/metadata:/var/lib/garage/meta
      - ${data:-.}/storage:/var/lib/garage/data
  garage_webui:
    extends:
      file: ../common.yaml
      service: base
    cap_drop:
      - ALL
    container_name: garage_webui
    depends_on:
      - garage
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    image: khairul169/garage-webui:${garage_webui_version:-latest}
    labels:
      homepage.group: Utils
      homepage.href: https://g.${domain:?}
      homepage.icon: sh-garage.svg
      homepage.name: Garage
      kuma.__docker:
      release_notes: "https://github.com/khairul169/garage-webui/releases"
      traefik.enable: "true"
      traefik.http.routers.garage_webui.entryPoints: "https"
      traefik.http.routers.garage_webui.middlewares: "localonly@file"
      traefik.http.routers.garage_webui.rule: "Host(`g.${domain:?}`)"
      traefik.http.services.garage_webui.loadbalancer.server.url: "http://garage_webui:3909"
    networks:
      proxy:
    volumes:
      - ${data:-.}/garage.toml:/etc/garage.toml:ro
