networks:
  proxy:
    external: true
services:
  garage:
    environment:
      TZ: ${timezone:-UTC}
    image: dxflrs/garage:${garage_version:-v2.3.0}
    deploy:
      labels:
        kuma.__docker:
        kuma.garage_s3.port.hostname: garage
        kuma.garage_s3.port.name: port_garage_s3
        kuma.garage_s3.port.notification_name_list: '["ntfy"]'
        kuma.garage_s3.port.port: 3900
        release_notes: "https://git.deuxfleurs.fr/Deuxfleurs/garage/releases"
        traefik.enable: "true"
        traefik.http.routers.garage.entryPoints: "https"
        traefik.http.routers.garage.middlewares: "localonly@file"
        traefik.http.routers.garage.rule: "Host(`s3.buncha.men`)"
        traefik.http.services.garage.loadbalancer.server.port: 3900
    networks:
      proxy:
    ports:
      - "3900:3900/tcp" ## s3 api
      - "3901:3901/tcp" ## rpc
    volumes:
      - /mnt/docker/garage/garage.toml:/etc/garage.toml:ro
      - /mnt/docker/garage/metadata:/var/lib/garage/meta
      - /mnt/docker/garage/storage:/var/lib/garage/data
  garage_webui:
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    image: khairul169/garage-webui:${garage_webui_version:-latest}
    deploy:
      labels:
        homepage.group: Files & Sharing
        homepage.href: https://g.buncha.men
        homepage.icon: sh-garage.svg
        homepage.name: Garage
        kuma.__docker:
        release_notes: "https://github.com/khairul169/garage-webui/releases"
        traefik.enable: "true"
        traefik.http.routers.garage_webui.entryPoints: "https"
        traefik.http.routers.garage_webui.middlewares: "localonly@file"
        traefik.http.routers.garage_webui.rule: "Host(`g.buncha.men`)"
        traefik.http.services.garage_webui.loadbalancer.server.port: 3909
    networks:
      proxy:
    volumes:
      - /mnt/docker/garage/garage.toml:/etc/garage.toml:ro
