networks:
  send: null
  proxy:
    external: true
services:
  copyparty:
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.2
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
    image: copyparty/iv:${copyparty_version:-latest}
    deploy:
      labels:
        homepage.group: Files & Sharing
        homepage.href: https://c.buncha.men
        homepage.icon: sh-copyparty.svg
        homepage.name: Copyparty
        kuma.__docker:
        release_notes: "https://github.com/9001/copyparty/releases"
        traefik.enable: "true"
        traefik.http.routers.copyparty.entryPoints: "https"
        traefik.http.routers.copyparty.middlewares: "localonly@file"
        traefik.http.routers.copyparty.rule: "Host(`c.buncha.men`)"
        traefik.http.services.copyparty.loadbalancer.server.port: 3923
    networks:
      proxy:
    stop_grace_period: 15s # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    user: ${uid:-1000}:${gid:-1000}
    volumes:
      - /mnt/docker/copyparty/conf:/cfg
      - /mnt/docker/copyparty/files:/w
  privatebin:
    image: privatebin/nginx-fpm-alpine:${privatebin_version:-stable}
    deploy:
      labels:
        homepage.group: Files & Sharing
        homepage.href: https://pb.buncha.men
        homepage.icon: sh-privatebin.svg
        homepage.name: PrivateBin
        kuma.__docker:
        release_notes: "https://privatebin.info/tag/release.html"
        traefik.enable: "true"
        traefik.http.routers.privatebin.entryPoints: "https"
        traefik.http.routers.privatebin.middlewares: "allowedIPs@file"
        traefik.http.routers.privatebin.rule: "Host(`pb.buncha.men`)"
        traefik.http.services.privatebin.loadbalancer.server.port: 8080
    networks:
      proxy: null
    read_only: true
    user: ${uid:-1000}:${gid:-1000}
    volumes:
      - /mnt/docker/privatebin/data:/srv/data
      - /mnt/docker/privatebin/tmp:/tmp
      - /mnt/docker/privatebin/run:/run
      - /mnt/docker/privatebin/nginx:/var/lib/nginx/tmp
  send:
    environment:
      BASE_URL: https://send.buncha.men
      DEFAULT_EXPIRE_SECONDS: 3600
      DOWNLOAD_COUNTS: 1,2,5
      EXPIRE_TIMES_SECONDS: 3600,86400,604800,2592000,31536000
      MAX_DOWNLOADS: 5
      MAX_EXPIRE_SECONDS: 31536000
      MAX_FILE_SIZE: 10737418240
      NODE_ENV: production
      REDIS_HOST: send_valkey
    image: registry.gitlab.com/timvisee/send:${send_version:-latest}
    deploy:
      labels:
        homepage.group: Files & Sharing
        homepage.href: https://send.buncha.men
        homepage.icon: sh-send-visee.svg
        homepage.name: Send
        kuma.__docker:
        release_notes: "https://gitlab.com/timvisee/send-instances/-/blob/master/README.md"
        traefik.enable: "true"
        traefik.http.routers.send.entryPoints: "https"
        traefik.http.routers.send.middlewares: "allowedIPs@file"
        traefik.http.routers.send.rule: "Host(`send.buncha.men`)"
        traefik.http.services.send.loadbalancer.server.port: 1443
    networks:
      proxy:
      send: null
    volumes:
      - /mnt/docker/send/app:/uploads
  send_valkey:
    image: valkey/valkey:${valkey_version:-9}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://github.com/valkey-io/valkey/releases"
    networks:
      send: null
    volumes:
      - /mnt/docker/send/valkey:/data
  slink:
    environment:
      IMAGE_COMPRESSION_QUALITY: 100
      IMAGE_MAX_SIZE: 50M
      IMAGE_STRIP_EXIF_METADATA: true
      ORIGIN: https://sl.buncha.men
      REQUIRE_SSL: true
      STORAGE_PROVIDER: local
      TZ: ${timezone:-UTC}
      USER_APPROVAL_REQUIRED: true
      USER_PASSWORD_MIN_LENGTH: 8
      USER_PASSWORD_REQUIREMENTS: 15 # bitmask of requirements
    image: anirdev/slink:${slink_version:-latest}
    deploy:
      labels:
        homepage.group: Files & Sharing
        homepage.href: https://sl.buncha.men
        homepage.icon: sh-slink.webp
        homepage.name: Slink
        kuma.__docker:
        release_notes: "https://github.com/andrii-kryvoviaz/slink/releases"
        traefik.enable: "true"
        traefik.http.routers.slink.entryPoints: "https"
        traefik.http.routers.slink.middlewares: "allowedIPs@file"
        traefik.http.routers.slink.priority: 30
        traefik.http.routers.slink.rule: "Host(`sl.buncha.men`)"
        traefik.http.services.slink.loadbalancer.server.port: 3000
        # No middleware for outbound images
        traefik.http.routers.slink-images.entrypoints: "https"
        traefik.http.routers.slink-images.priority: 50
        traefik.http.routers.slink-images.rule: "Host(`sl.buncha.men`) && PathPrefix(`/image/`)"
    networks:
      proxy: null
    user: ${uid:-1000}:${gid:-1000}
    volumes:
      - /mnt/docker/slink/data:/data
      - /mnt/docker/slink/db:/app/var/data
      - /mnt/docker/slink/images:/app/slink/images
