networks:
  proxy:
    external: true
services:
  wgeasy:
    environment:
      INSECURE: false
    image: ghcr.io/wg-easy/wg-easy:${wgeasy_version:-15}
    deploy:
      labels:
        homepage.group: Access & Security
        homepage.href: https://vpn.buncha.men
        homepage.icon: sh-wireguard.svg
        homepage.name: WG-Easy
        kuma.__docker:
        release_notes: "https://github.com/wg-easy/wg-easy/releases"
        traefik.enable: "true"
        traefik.http.routers.wgeasy.entryPoints: "https"
        traefik.http.routers.wgeasy.middlewares: "localonly@file"
        traefik.http.routers.wgeasy.rule: "Host(`vpn.buncha.men`)"
        traefik.http.services.wgeasy.loadbalancer.server.port: 51821
    networks:
      proxy:
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    volumes:
      - /mnt/docker/wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
