networks:
  proxy:
    external: true
services:
  netbootxyz:
    environment:
      PGID: ${gid:-1000}
      PUID: ${uid:-1000}
      TZ: ${timezone:-UTC}
      WEB_APP_PORT: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
    image: ghcr.io/netbootxyz/netbootxyz:${netbootxyz_version-latest}
    deploy:
      labels:
        kuma.__docker:
        release_notes: "https://netboot.xyz/docs/community/changelog"
        traefik.enable: "true"
        traefik.http.routers.netbootxyz.entryPoints: "https"
        traefik.http.routers.netbootxyz.middlewares: "localonly@file"
        traefik.http.routers.netbootxyz.rule: "Host(`nb.buncha.men`)"
        traefik.http.services.netbootxyz.loadbalancer.server.port: 3000
    networks:
      proxy: null
    ports:
      - "69:69/udp"
    volumes:
      - /mnt/docker/netbootxyz/config:/config:rw
      - /mnt/docker/netbootxyz/assets:/assets:rw
