name: Create PR and merge

on:
  workflow_run:
    workflows:
      - Validate stacks
    types:
      - completed

jobs:
  create-and-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download commit message
        uses: actions/download-artifact@v4
        with:
          name: last-commit-message
          path: ./artifact

      - name: Read last commit message
        id: commitmsg
        run: |
          # If you uploaded $GITHUB_OUTPUT, extract msg line; otherwise read commit.msg
          if [ -f ./artifact/$GITHUB_OUTPUT ]; then
            grep '^msg=' ./artifact/$GITHUB_OUTPUT | sed 's/^msg=//g' > commit.msg || true
          fi
          if [ -f ./artifact/commit.msg ]; then
            cat ./artifact/commit.msg > commit.msg
          fi
          echo "msg=$(cat commit.msg || true)" >> $GITHUB_OUTPUT

      - name: Create PR and Merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const commitMessage = `${{ steps.commitmsg.outputs.msg }}` || '';
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Auto-merge: Dev to Main',
              head: 'dev',
              base: 'main',
              body: `## Latest Commit Message\n**${commitMessage}**\n\n---\n*Automated PR created after successful CI run*`
            });

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'merge'
            });
